// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9s93i10TYHbgeDIieZjtksVJfUKC3ck',
    appId: '1:861311883307:web:7e50b81696a6ff59b4b26e',
    messagingSenderId: '861311883307',
    projectId: 'carbontrack-pro',
    authDomain: 'carbontrack-pro.firebaseapp.com',
    databaseURL: 'https://carbontrack-pro-default-rtdb.firebaseio.com',
    storageBucket: 'carbontrack-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDHk79NGMpU43UF8f4qGlwPzOvH_00QQ',
    appId: '1:861311883307:android:f61083b8a4f475e8b4b26e',
    messagingSenderId: '861311883307',
    projectId: 'carbontrack-pro',
    databaseURL: 'https://carbontrack-pro-default-rtdb.firebaseio.com',
    storageBucket: 'carbontrack-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwB7RRjwxxQMoD_ddGnC-lHxFox6d6HY',
    appId: '1:861311883307:ios:c534e0696309e7c9b4b26e',
    messagingSenderId: '861311883307',
    projectId: 'carbontrack-pro',
    databaseURL: 'https://carbontrack-pro-default-rtdb.firebaseio.com',
    storageBucket: 'carbontrack-pro.appspot.com',
    iosBundleId: 'com.example.carbonFoodprintPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlwB7RRjwxxQMoD_ddGnC-lHxFox6d6HY',
    appId: '1:861311883307:ios:b7727c833f2db56fb4b26e',
    messagingSenderId: '861311883307',
    projectId: 'carbontrack-pro',
    databaseURL: 'https://carbontrack-pro-default-rtdb.firebaseio.com',
    storageBucket: 'carbontrack-pro.appspot.com',
    iosBundleId: 'com.example.carbonFoodprintPro.RunnerTests',
  );
}
